<link rel="stylesheet" href="../public/datatable/bootstrap.css">
<link rel="stylesheet" href="../public/datatable/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="../public/css/estilos.css?3.2">
<link rel="stylesheet" href="../public/css/inicio.css?1.2">
<link rel="stylesheet" href="../public/css/login.css?1.1">
<link rel="stylesheet" href="../public/css/alerts.css?1.1">
<link rel="stylesheet" href="../public/css/header.css">
<link rel="stylesheet" href="../public/css/scroll.css">
<link rel="stylesheet" href="../public/css/informacion.css">
<link rel="stylesheet" href="../public/css/footer.css">
<link rel="stylesheet" href="../public/css/tabla.css?1.2">
<link rel="stylesheet" href="../public/css/modal.css?1.1">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">

<script type="text/javascript" src="../public/jquery-3.5.1.js"></script>
<script type="text/javascript" src="../public/js/main.js?2.5"></script>
<script type="text/javascript" src="../public/datatable/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="../public/datatable/dataTables.bootstrap4.min.js"></script>
